backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

logo_url: https://www.itsagroalimentarete.it/templates/it/its/images/logo.png
locale: 'it'

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "entries" # Used in routes, e.g., /admin/collections/blog
    label: "Treadmill Entries" # Used in the UI
    folder: "/content/entries" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {label: "Colonna", name: "colonna", widget: "select", options : [{ label: "Colonna Sinistra", value: "sinistra" },{ label: "Colonna Destra", value: "destra" }] }
      - {label: "In Evidenza", name: "evidenza", widget: "boolean", default: false, required: false}
      - { label: "Immagine di copertina", name: "cover", widget: "image" }
      - { label: "Sottotitolo", name: "subtitle", widget: "string" }
      - { label: "Link per Video", name: "videourl", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }
  