on:
  push:
    branches:
          - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'

    - name: Build
      run: hugo -D --minify
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        local-dir: ./public/
        server-dir: public_html/orientamento-21-23/
        server: lhcp3195.webapps.net
        username: vt4g7hhh
        password: ${{ secrets.FTP_PASSWORD }}